item {
    id: 1
    name: 'USB cable'
}

item {
    id: 2
    name: 'brown box'
}

item {
    id: 3
    name: 'white box'
}

item {
    id: 4
    name: 'green bottle'
}

item {
    id: 5
    name: 'brown bottle'
}

item {
    id: 6
    name: 'green square bottle'
}
